global:
  scrape_interval: 15s # How frequently to poll targets
  evaluation_interval: 15s

# Scraping configs targeting microservices metrics endpoints
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'menu-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['menu-service:8082']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8084']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']

  - job_name: 'report-service'
    static_configs:
      - targets: ['report-service:8086']
