input {
  # Filebeat outputs to Logstash port 5044
  beats {
    port => 5044
  }
}

filter {
  # Parse microservices console JSON logs
  if [headers][content_type] == "application/json" or [message] =~ /^\{.*/ {
    json {
      source => "message"
      target => "log_details"
    }
  }
  
  # Inject index names based on docker container labels
  mutate {
    add_field => { "service_name" => "%{[container][name]}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "bistro-microservices-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}
